### ISSUE TITLE
Fn trait objects

### ISSUE THREAD

**Issue by sweirich** [GaloisInc/mir-json#13]
This rust function:

```
fn call_with_one(some_closure: &Fn(i32) -> i32) -> i32 {
    some_closure(1)
}
```
produces the following (pretty-printed) mir-json:
```
 ::call_with_one[0](_1 : &dynamic ops::function::Fn) ->  i32 {
let mut _0 : i32;
let mut _2 : &dynamic ops::function::Fn;
let mut _3 : (i32);
bb0: {
   StorageLive(_2);
   _2 = use(_1);
   StorageLive(_3);
   _3.0 = use(1);
   call(_0 = ops::function::Fn::call<dynamic ops::function::Fn,(i32)>(_2,_3)
       ,bb1)
}
bb1: {
   StorageDead(_3);
   StorageDead(_2);
   return;
}
}
```

In the rust source, the argument and return types of the closure are part of the rust type `&Fn(i32) -> i32` but they don't appear in the MIR type `&dynamic ops::function::Fn`.
Is this information available? 

I can work around it by gathering these types from other places, but it's fragile and makes the code really messy. In fact, I'm just about to drop support for this test just to improve the code.

**Comment by epdtry** [comment]
As of afb6116cfdda8f98be488eb0f9ae5bb907f47855, `mir-json` outputs complete predicate information for `TyKind::Dynamic` types.

The output for a `TyKind::Dynamic` now has a `predicates` field:

```javascript
{
    "kind": "Dynamic",
    "predicates": [ /* ... */ ],
}
```

Note the `data` field, which contained the def ID of the principal trait, is no longer present.  The same information is now available from `predicates[0]`: if `predicates[0].kind` is `Trait`, then `predicates[0].trait` contains the principal trait's def ID.  (For our version of `rustc`, `predicates[0].kind` is always `Trait`, but this is no longer true in newer versions.)

## Predicates

There are three kinds of predicates.  I'll use `dyn Fn(bool) -> char + Send` as an example, since it includes all three.  Note that `Fn(A, B) -> C` desugars to `Fn<(A, B), Output=C>`, and is represented as such in the `mir-json` output.

The representation of `dyn Fn(bool) -> char + Send` looks like this:

```javascript
{
    "kind": "Dynamic",
    "predicates": [
        {
            // #1
            "kind": "Trait",
            "trait": "::ops[0]::function[0]::Fn[0]",
            "substs": [
                {
                    "kind": "Tuple",
                    "tys": [ { "kind": "Bool" } ]
                }
            ]
        },
        {
            // #2
            "kind": "Projection",
            "proj": "::ops[0]::function[0]::FnOnce[0]::Output[0]",
            "substs": [
                {
                    "kind": "Tuple",
                    "tys": [ { "kind": "Bool" } ]
                }
            ],
            "rhs_ty": { "kind": "Char" }
        },
        {
            // #3
            "kind": "AutoTrait",
            "trait": "::marker[0]::Send[0]"
        }
    ]
}
```

### `Trait`

The `Trait` predicate kind asserts that the concrete type underlying the `TyKind::Dynamic` implements a specific trait.  The `trait` field gives the def ID of the trait, and `substs` gives the type arguments to the trait.  Note that while `Self` appears as a generic parameter in some uses of traits, here it is omitted from the `substs`, since `Self` is implicitly the concrete type of the `Dynamic`.

Currently there can be at most a single `Trait` bound, which (if present) is always `predicates[0]`.  I don't know of any plans to change this on the `rustc` side.  The trait indicated by the lone `Trait` bound is called the "principal trait".

In the example, predicate `#1` says that `Self: Fn<(bool,)>`.

### `Projection`

The `Projection` predicate kind asserts that an associated type of the concrete type must be equal to a particular type.  The `proj` field gives the def ID of the associated type, `substs` gives the type arguments (as in `Trait`), and `rhs_ty` is the type that the associated type must match.

The associated type listed in `proj` should always belong to the principal trait.  There should always be a `Projection` for every associated type of the principal trait, since otherwise it would be impossible to determine the signatures of some methods in the vtable.

In the example, predicate `#2` says that `<Self as Fn<(bool,)>>::Output == char`.

### `AutoTrait`

The `AutoTrait` predicate kind asserts that the concrete type implements an auto trait, such as `Send` or `Sync`.  This is similar to the `Trait` kind, but is only used for `auto trait`s, which have no methods and no type parameters.  As a result, the JSON for `AutoTrait` predicates contains only the `trait` field, with no `substs`.

There can be any number of `AutoTrait` predicates.  They're used both for the standard auto traits (`Send`, `Sync`, and a few others) and for user-defined `auto trait`s.

In the example, predicate `#3` says that `Self: Send`.


## More examples

* `dyn Any`: Has only a `Trait` predicate, for `Self: Any`.

* `dyn Iterator<Item=i32>`: Has a `Trait` predicate for `Self: Iterator`, and a `Projection` predicate for `<Self as Iterator>::Item == i32`.

* `dyn Any + Sync + Send`: Has a `Trait` predicate for `Self: Any`, and two `AutoTrait` predicates for `Self: Sync` and `Self: Send`.

* `dyn Send + Sync`: In our version of `rustc`, this produces a `Trait` predicate for `Send`, and an `AutoTrait` predicate for `Sync`.  It makes `Send` the principal trait because it appears first in the source code.   I believe newer versions of `rustc` would use `AutoTrait` for both, and have no `Trait` predicate at all.  (Our `rustc` rejects conversions of `dyn Send + Sync` to `dyn Sync + Send` because the two types have different principal traits.  Newer versions accept this conversion.)

**Comment by epdtry** [comment]
I've also pushed GaloisInc/mir-verifier@990370099f6ed978db4b39b0061aef9135ec2936, which is a quick hack to make parsing work with the new `TyDynamic` format (using `predicates[0].trait` instead of `data`)

**Comment by sweirich** [comment]
Thanks.  Are the predicates here related to the trait predicates elsewhere in the AST. It doesn't look like they have the same JSON structure, but they look related.  
(For reference, here is the current parser for `Predicate` --- note that it looks for either "trait_pred" or "trait_proj" instead of using "kind".)

```
instance FromJSON Predicate where
    parseJSON obj = case obj of
      Object v -> do
        mpobj <- v .:? "trait_pred"
        case mpobj of
          Just pobj -> do
            TraitPredicate <$> pobj .: "trait" <*> pobj .: "substs"
          Nothing -> do
            mpobj <- v .:? "trait_proj"
            case mpobj of
              Just ppobj -> do
                pobj <- ppobj .: "projection_ty"
                TraitProjection <$> (TyProjection <$> pobj .: "item_def_id" <*> pobj .: "substs")
                                <*> ppobj .: "ty"
              Nothing -> return UnknownPredicate
      String t | t == "unknown_pred" -> return UnknownPredicate
      wat -> Aeson.typeMismatch "Predicate" wat   
```

**Comment by epdtry** [comment]
They are distinct types within the compiler.  For example:
https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TraitRef.html
https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.ExistentialTraitRef.html

They have similar structure but slightly different semantics: the `Existential` versions omit the `Self` type from their `substs`, since they implicitly constrain the concrete type of the `dyn`.  So if a trait has `N` type parameters in its `generics` field (including `Self`, which is always parameter \#0), a `TraitRef` for that trait will have `N` `substs`, but an `ExistentialTraitRef` will have only `N - 1`.
