### ISSUE TITLE
negative integers

### ISSUE THREAD

**Issue by sweirich** [GaloisInc/mir-json#5]
mir-json prints -1 as 1.8446744073709552e+19

**Comment by atomb** [comment]
I believe this is fixed in 358bd291. The compiler represents all `SwitchInt` cases as 128-bit unsigned values internally. These are now printed out as strings instead of JSON numbers (which are interpreted as double-precision floating point). They'll still need to be parsed as unsigned decimal values and cast to the appropriate (possibly-signed) type inside `mir-verifier`.

I'm going to leave the issue open until you confirm that this is fixed in a way that works for you, though.

**Comment by sweirich** [comment]
This works, and incorporated into mir-verifier at 738b81675cbd4cb5fb778fc13111e27faa59fa41.
